### Universidad Autonoma de Aguascalientes
### Centro de Ciencias Basicas
### Departamento de Ciencias de la Computacion
### Carrera: Ingenieria en Computacion Inteligente
### Materia: Machine Learning
### Profesor: Dr. Francisco Javier Luna Rosas
### Alumno: Diego Emilio Moreno Sanchez

#### Práctica No. 5. Redes Neuronales

In [1]:
import  os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier # Multi Layer Perceptron Classifier
from sklearn.metrics import confusion_matrix
from pandas import DataFrame

/tmp/ipykernel_133588/2718724540.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
datos = pd.read_csv('iris.csv', delimiter=';', decimal='.')
print(datos.shape)
print(datos.head())

(150, 5)
   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa


#### Dejamos las variables predictoras en x

In [3]:
x = datos.iloc[:, :4]
print(x.head())

   s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2


#### Dejar la variable a predecir en y

In [4]:
y = datos.iloc[:, 4:5]
print(y.head())

     tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa


#### Separar datos 70% entrenamiento, 30% testing

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, random_state = 0)

#### Mediante el constructor inicializamos la red neuronal
nota. Por defecto se usan 100 nodos en cada capa oculta, "solver" es el metodo de optimización (este nos ayudará para el gradiente descendente, hay muchos, como adam, stocastic, ...)

In [6]:
red = MLPClassifier()
print(red)

MLPClassifier()


#### Entrenando al modelo

Se logra llamando al método fit.

In [7]:
red.fit(x_train, y_train.iloc[:,0].values)

/home/yeyo/code/school_code/semester_06/aprendizaje_inteligente/ml/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

#### Imprimiendo las predicciones en testing

In [9]:
print("Las predicciones en testing son: {}".format(red.predict(x_test)))

Las predicciones en testing son: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'virginica' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'virginica' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'virginica'
 'setosa' 'setosa']


#### Calculando los índices de calidad de la predicción

In [16]:
# Funcion
def indices_general(MC, nombres = None):
    precision_global = np.sum(MC.diagonal()) / np.sum(MC)
    error_global = 1 - precision_global
    precision_categoria = pd.DataFrame(MC.diagonal() / np.sum(MC, axis = 1)).T
    if nombres != None:
        precision_categoria.columns = nombres
    return {"Matriz de confusion": MC,
                  "Precision Global": precision_global,
                  "Error Global": error_global,
                  "Precision por categoria": precision_categoria
           }

In [17]:
prediccion = red.predict(x_test)
mc = confusion_matrix(y_test, prediccion)
indices = indices_general(mc, list(np.unique(y)))
for i in indices:
    print("\n%s:\n%s"%(i, str(indices[i])))


Matriz de confusion:
[[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]

Precision Global:
0.9333333333333333

Error Global:
0.06666666666666665

Precision por categoria:
   setosa  versicolor  virginica
0     1.0    0.833333        1.0
